### PR TITLE
Hide notes if no notes

### PR DESCRIPTION
**Pull request by jkudish**
Rather than displaying an empty notes box, this hides the notes box completely if there are no notes.

Let me know what you think!

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
Does this make the right column work as intended?

I haven't tested it but if it works the same way I will accept it :3 can you post a screen? rather busy atm.

Thanks!

**Comment by jkudish** [comment]
Sorry for the delay, seems I didn't get the notification for this...

Yes because notes was position absolute and the right column has a margin-left, the position is left unchanged. 

Here's how it looks:

image

**Comment by ConsoleTVs** [comment]
I'm also sorry, did not check it myself either. Seems good to go!

**Comment by jkudish** [comment]
Cheers!

**Pull request merged**
